
[functions.verifyCode]
enabled = true
verify_jwt = true
import_map = "./functions/verifyCode/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verifyCode/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verifyCode/*.html" ]

[functions.signupPublic]
enabled = true
verify_jwt = true
import_map = "./functions/signupPublic/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/signupPublic/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/signupPublic/*.html" ]

[functions.signupUser]
enabled = true
verify_jwt = false
import_map = "./functions/signupUser/deno.json"
entrypoint = "./functions/signupUser/index.ts"

[functions.signin]
enabled = true
verify_jwt = false
import_map = "./functions/signin/deno.json"
entrypoint = "./functions/signin/index.ts"

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-world/*.html" ]

[functions.generate-presigned-url]
enabled = true
verify_jwt = false
entrypoint = "./functions/generate-presigned-url/index.ts"

[functions.send-announcement-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-announcement-notification/index.ts"
